FROM mattias/dev
MAINTAINER Mattias Appelgren, mattias@ppelgren.se

# Install python and tools
RUN apt-get --yes --quiet install python-dev python-pip python-setuptools

# Install virtualenv
RUN pip install virtualenv
